version: "3"

services:

  postgres:
    image: postgres:15
    environment:
      - JwtSettings__Secret=${JWT_SECRET}
      - ConnectionStrings__DefaultConnection=Server=db;Database=telematics;User Id=postgresrs;Password=${DB_PASSWORD};
    ports:
      - "5432:5432"

  telemetry-service:
    build: ../services/telemetry-service
    ports:
      - "5000:80"
    depends_on:
      - postgres